spring:
  application:
    name: mym-email-and-notification-service
  mail:
    host: smtp.gmail.com
    username: company.forwork123@gmail.com
    password: vydlyiodsqkoztrp
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
  rabbitmq:
    host: localhost
    port: 5672
    username: mym_rkumar0206
    password: mym_password_123
    virtual-host: ${rabbitmqserver.env:mym-env-test}

server:
  port: 8572

myEureka:
  username: 'rkumar0206'
  password: '123456789P'

eureka:
  client:
    service-url:
      defaultZone: http://${myEureka.username}:${myEureka.password}@localhost:8845/eureka
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30

app-gateway:
  host: ${mym-gateway.host:localhost} #default localhost
  port: ${mym-gateway.port:8562}

connection:
  baseUrl: 'http://${app-gateway.host}:${app-gateway.port}'

routing-keys:
  accountVerification: mym.user.account.verification
  emailUpdateOtp: mym.user.email.update.otp
  passwordReset: mym.user.password.reset

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
      base-path: "/mym/${spring.application.name}/actuator"